version: '3.5'

services:
  appjobsphp:
    build:
      context: ./
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        uid: ${UID:-1000}
        gid: ${GID:-1000}
    container_name: appjobs-php
    volumes:
      - .:/var/www/appjobs
      - ./docker/php-fpm/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - appjobs

  appjobsnginx:
    container_name: appjobs-nginx
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - .:/var/www/appjobs
    ports:
      - "80:80"
    networks:
      - appjobs

networks:
  appjobs:
